### ISSUE TITLE
用微信开发者构建时找不到npm入口文件

### ISSUE THREAD

**Issue by PeakJ** [wechat-miniprogram/slide-view#1]
用最新的开发者工具构建npm的时候报如下错误：

![image](https://user-images.githubusercontent.com/15241539/44075574-cfec7e98-9fcf-11e8-8372-028d586e4956.png)

**Comment by JuneAndGreen** [comment]
这是先前误把 demo 中的代码提交到 npm 导致，在 0.0.3 之后的版应该已经修复了。
