### ISSUE TITLE
有时候会遇到部分组件划不出来的情况

### ISSUE THREAD

**Issue by CorgiTT** [wechat-miniprogram/slide-view#4]
![img](https://raw.githubusercontent.com/Xavier0818/damai/master/public/img/gif.gif)
演示图

**Comment by JuneAndGreen** [comment]
给一下能复现问题的demo？代码片段也行。

**Comment by Xavier0818** [comment]
> 给一下能复现问题的demo？代码片段也行。

**Comment by Xavier0818** [comment]
wechatide://minicode/nAa0fqmL7Z3B

我发现是偶现问题，大部分情况下是好的

**Comment by CorgiTT** [comment]
而且我发现总是第一个slider-view有问题，wxml上的页面结构和其他的不一样，是不是因为异步请求再加上组件加载的顺序问题导致的
![img](https://raw.githubusercontent.com/Xavier0818/damai/master/public/img/1540435998(1).png)

**Comment by Xavier0818** [comment]
> 给一下能复现问题的demo？代码片段也行。

**Comment by li2go** [comment]
😄

**Comment by CorgiTT** [comment]
我已经复现了这个问题：同一个位置，数据切换后，之前没有right侧栏不能划出，会影响后面有right侧栏也无法划出

没有right侧栏的情况下，没有划出；
进行数据的切换；
有了right侧栏的情况下，依然没有划出；

相反的，

有right侧栏的情况下，可以划出；
进行数据的切换；
没有right侧栏的情况下，依然可以划出；

具体操作可以，看看演示图或者代码片段：wechatide://minicode/LeYyCrmU7K3O

![img](https://raw.githubusercontent.com/Xavier0818/damai/master/public/img/gif.gif)

**Comment by JuneAndGreen** [comment]
@Xavier0818 你这个问题在于你是这个组件渲染完之后再去改 `slot="right"` 那部分的宽度，而这个组件里依赖到的宽度没有即时更新。因为组件内部无法监听到 `composed tree` 的变化，所以目前的 **0.0.4** 版本给组件提供了一个 `updateRight` 方法。你在更新了宽度之后需要再手动调一下 updateRight 方法来更新组件内依赖的变量。

**Comment by christophermitchell070** [comment]
FU
