### ISSUE TITLE
Component is not found in path "pages/index/miniprogram-slide-view" (using by "pages/index/index")

### ISSUE THREAD

**Issue by weiki-li** [wechat-miniprogram/slide-view#5]
在需要使用 slide-view 的页面 page.json 中添加 slide-view 自定义组件配置
{
  "usingComponents": {
    "slide-view": "miniprogram-slide-view"
  }
}

**Comment by JuneAndGreen** [comment]
请阅读文档，使用 npm 构建：https://developers.weixin.qq.com/miniprogram/dev/devtools/npm.html
